package app.campusconnect.domain;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_DECLINED,
    BOOKING_CANCELLED,
    BOOKING_RESCHEDULED,
    BOOKING_REMINDER,
    BOOKING_COMPLETED,
    MESSAGE_RECEIVED,
    REVIEW_RECEIVED,
    REVIEW_REPLY,
    PROVIDER_APPROVED,
    PROVIDER_REJECTED,
    PAYOUT_PAID
}
